name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: true

env:
  REGISTRY: "registry.digitalocean.com/finalassignment"
  IMAGE_NAME: "fastapi-sentiment"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7} .

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: path/to/image.tar

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i path/to/image.tar

      - name: Push image to DigitalOcean Container Registry
        run: docker push $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}


  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,DIGITALOCEAN_ACCESS_TOKEN,GITHUB_SHA
          script: |
            # Login to registry
            echo $DIGITALOCEAN_ACCESS_TOKEN | docker login registry.digitalocean.com -u doctl --password-stdin
            # Stop running container
            docker stop $IMAGE_NAME || true
            # Remove old container
            docker rm $IMAGE_NAME || true
            # Run a new container from a new image
            docker run -d \
            --restart always \
            --name $IMAGE_NAME \
            -p 4001:4001 \
            $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}
